# Generated by Django 4.0.4 on 2022-04-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='toilet_posts.author')),
            ],
        ),
        migrations.DeleteModel(
            name='ToiletModel',
        ),
    ]
