# Generated by Django 4.0.4 on 2022-04-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0003_alter_toilet_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='author',
        ),
    ]
