# Generated by Django 4.0.4 on 2022-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0004_remove_toilet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
