# Generated by Django 4.0.4 on 2022-04-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0005_toilet_author_alter_toilet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='location',
        ),
    ]
