# Generated by Django 4.0.4 on 2022-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0006_remove_toilet_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='author',
        ),
        migrations.AddField(
            model_name='toilet',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
