# Generated by Django 4.0.4 on 2022-04-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0007_remove_toilet_author_toilet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
