# Generated by Django 4.0.4 on 2022-04-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0008_toilet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='user_tg_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
