# Generated by Django 4.0.4 on 2022-04-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0010_toilet_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user_name',
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
