# Generated by Django 4.0.4 on 2022-04-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0011_remove_author_user_name_author_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='post_count',
            field=models.IntegerField(null=True),
        ),
    ]
