# Generated by Django 4.0.4 on 2022-05-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0012_author_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='user_tg_id',
            field=models.CharField(max_length=12),
        ),
    ]
