# Generated by Django 4.0.4 on 2022-05-03 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0015_toilet_created_date_toiletpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToiletGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='images/gallery')),
            ],
        ),
        migrations.AlterField(
            model_name='toilet',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 15, 21, 18, 280666), null=True),
        ),
        migrations.DeleteModel(
            name='ToiletPicture',
        ),
        migrations.AddField(
            model_name='toiletgallery',
            name='toilet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='toilet_posts.toilet'),
        ),
    ]
