# Generated by Django 4.0.4 on 2022-05-05 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0016_toiletgallery_alter_toilet_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 8, 19, 24, 4814, tzinfo=utc), null=True),
        ),
    ]
