# Generated by Django 4.0.4 on 2022-05-05 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0017_alter_toilet_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
