# Generated by Django 4.0.4 on 2022-05-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0018_alter_toilet_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='img_tg_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
