# Generated by Django 4.0.4 on 2022-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0019_toilet_img_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgBytes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_tg_bytes', models.TextField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='img_tg_id',
        ),
    ]
