# Generated by Django 4.0.4 on 2022-05-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_posts', '0020_imgbytes_remove_toilet_img_tg_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgBytes',
        ),
    ]
